version: '3.7'
services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: lukaswire/swa-user-service:latest
    container_name: user-service-under-tests
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - user-service-contracts-net

  db:
    image: postgres:12.2
    container_name: user-service-under-test-db
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - user-service-contracts-net

networks:
  user-service-contracts-net:
    driver: bridge